production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost 
    port: 8983
    solr_home: solr 
    log_level: INFO

#development:
  #solr:
    #hostname: ec2-184-73-233-18.compute-1.amazonaws.com 
    #port: 8983
    #solr_home: solr 
    #path: solr/development
    #log_level: INFO

stagingsmall:
  solr:
    hostname: localhost 
    port: 8983
    solr_home: solr
    log_level: WARNING

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
