production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    solr_home: solr
    log_level: INFO

stagingsmall:
  solr:
    hostname: localhost
    port: 8982
    solr_home: solr
    read_timeout: 2
    open_timeout: 0.5

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
