---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: poliana.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-b55177d0
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - poliana_staging_default
  - poliana_staging_web
  - poliana_staging_web_tools
  - poliana_staging_staging
  - poliana_staging_apache
  - poliana_staging_app
  - poliana_staging_passenger
  - poliana_staging_collectd
  - poliana_staging_common
  - poliana_staging_monit
  - poliana_staging_db
  - poliana_staging_mysql
  - poliana_staging_mysql_master
  - poliana_staging_elasticsearch
  - poliana_staging_examples
  - poliana_staging_graphite_server
  - poliana_staging_graphite_web
  - poliana_staging_graylog_elasticsearch
  - poliana_staging_graylog_mongodb
  - poliana_staging_mongodb
  - poliana_staging_graylog_server
  - poliana_staging_graylog_web
  - poliana_staging_haproxy
  external_host: ec2-54-237-41-38.compute-1.amazonaws.com
  external_ip: 54.237.41.38
  internal_host: ip-10-28-136-87.ec2.internal
  internal_ip: 10.28.136.87
  zone: us-east-1c
  provider: aws
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
