---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: stagingsmall
  domain: poliana.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-7c92895d
  image_type: m1.small
  image_id: ami-b6089bdf
  security_groups:
  - poliana_stagingsmall_default
  - poliana_stagingsmall_web
  - poliana_stagingsmall_web_tools
  - poliana_stagingsmall_stagingsmall
  - poliana_stagingsmall_apache
  - poliana_stagingsmall_app
  - poliana_stagingsmall_passenger
  - poliana_stagingsmall_collectd
  - poliana_stagingsmall_common
  - poliana_stagingsmall_monit
  - poliana_stagingsmall_db
  - poliana_stagingsmall_mysql
  - poliana_stagingsmall_mysql_master
  - poliana_stagingsmall_elasticsearch
  - poliana_stagingsmall_examples
  - poliana_stagingsmall_graphite_server
  - poliana_stagingsmall_graphite_web
  - poliana_stagingsmall_graylog_elasticsearch
  - poliana_stagingsmall_graylog_mongodb
  - poliana_stagingsmall_mongodb
  - poliana_stagingsmall_graylog_server
  - poliana_stagingsmall_graylog_web
  - poliana_stagingsmall_haproxy
  external_host: ec2-54-226-229-127.compute-1.amazonaws.com
  external_ip: 54.226.229.127
  internal_host: ip-10-11-139-179.ec2.internal
  internal_ip: 10.11.139.179
  zone: us-east-1a
  provider: aws
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
